[[sites]]
  id = "comfi.es"
  url = "https://comfi.es/"
  css = "https://comfi.es/src/webcircle.css"

[[sites]]
  id = "dystopia.club"
  url = "https://dystopia.club/"
  css = "https://dystopia.club/circle.css"

[[sites]]
  id = "lost-in-walmart.blog"
  url = "https://lost-in-walmart.blog/"
  css = "https://lost-in-walmart.blog/circular.css"
  
[[sites]]
  id = "foreverliketh.is"
  url = "https://foreverliketh.is/"
  css = "https://comfi.es/src/webcircle.css"
